### ISSUE TITLE
`s.unref` is not a function

### ISSUE THREAD

**Issue by NetOpWibby** [rethinkdb/rethinkdb-ts#103]
I'm trying to use this with Deno and connect to my database. I am using [esm.sh](https://esm.sh) as a way to enable usage of Node modules with Deno projects. Here's the error message:

```
ReqlDriverError: Unable to establish connection, see cause for more info.
    at nt.reconnect (https://esm.sh/v86/rethinkdb-ts@2.4.21/deno/rethinkdb-ts.js:23:17814)
    at async Function._.r.connect (https://esm.sh/v86/rethinkdb-ts@2.4.21/deno/rethinkdb-ts.js:39:1454)
Caused by TypeError: s.unref is not a function
    at https://esm.sh/v86/rethinkdb-ts@2.4.21/deno/rethinkdb-ts.js:2:17194
    at new Promise (<anonymous>)
    at sr (https://esm.sh/v86/rethinkdb-ts@2.4.21/deno/rethinkdb-ts.js:2:17142)
    at nt.reconnect (https://esm.sh/v86/rethinkdb-ts@2.4.21/deno/rethinkdb-ts.js:23:17745)
    at Function._.r.connect (https://esm.sh/v86/rethinkdb-ts@2.4.21/deno/rethinkdb-ts.js:39:1462)
    at https://esm.sh/v86/@webb/ensure-database@2022.3.1-4.1/deno/ensure-database.js:2:3237
    at f (https://esm.sh/v86/@webb/ensure-database@2022.3.1-4.1/deno/ensure-database.js:2:2673)
    at Object.next (https://esm.sh/v86/@webb/ensure-database@2022.3.1-4.1/deno/ensure-database.js:2:1977)
    at https://esm.sh/v86/@webb/ensure-database@2022.3.1-4.1/deno/ensure-database.js:2:1685
    at new Promise (<anonymous>)
```

The [`delay` function](https://github.com/rethinkdb/rethinkdb-ts/blob/main/src/util/index.ts#L18-L26=) is the only reference to `unref` I could find:

```ts
function delay(timeInMs: number, options?: { unref: boolean }): Promise<void> {
  return new Promise((resolve) => {
    const timer = setTimeout(resolve, timeInMs);

    if (options && options.unref) {
      timer.unref();
    }
  });
}
```

From a quick search about this issue, maybe using `clearTimeout` would be a better replacement? Idk.

**Comment by atassis** [comment]
I dont know the deno, have to research it for a better approach of making it. Won't make any changes until they are described properly, the main goal is to make it stable for node js. We are unrefing here so the process ld be able to stop immediately, without waiting for the timeout to finish, so if clearTimeout does that properly- I'll do the change by myself

**Comment by NetOpWibby** [comment]
All good, I just pulled this module into my Deno project and changed the code to:

```ts
export function delay(timeInMs: number, options?: { unref: boolean }): Promise<void> {
  return new Promise(resolve => {
    const timer = setTimeout(resolve, timeInMs);

    if (options && options.unref)
      clearTimeout(timer);
  });
}
```

I'll probably just end up forking your module for Deno once I figure out solutions to existing (and new) `// @ts-ignore`s.

**Comment by atassis** [comment]
Ah, no, the thing you do- you create the timeout and then immediately clear it, so the delay function will never resolve

**Comment by atassis** [comment]
Found [this](https://doc.deno.land/https://deno.land/std@0.127.0/node/timers.ts/~/setUnrefTimeout)  for deno, but that's a different api, don't know now how to manage this for both deno and node js

**Comment by NetOpWibby** [comment]
Oh wow, didn't know that existed! I'll check it out.

**Comment by atassis** [comment]
I can't find a way to make an isomorphic code which uses different methods depending on an env it is executed (node ".unref" and deno "setUnref..." stuff)

**Comment by atassis** [comment]
Can you describe how do you use this repo in deno?

**Comment by NetOpWibby** [comment]
I can add code if that helps.

**Comment by atassis** [comment]
I don't quite get how rethinkdb-ts is related to the message above=)

**Comment by NetOpWibby** [comment]
I'm using this module for my project. I can close this issue though, I fixed it for my purposes.

**Comment by atassis** [comment]
I am interested how do you run it in deno
Maybe I can do some workarounds right in repo so it can be run in any environment

**Comment by NetOpWibby** [comment]
It's literally just a simple lookup query:

```ts
  for await(const pack of socket) {
    const [data, remoteAddr] = pack;
    const query = packet.decode(Buffer(data));
    const { questions } = query;

    if (!query.questions.length) /// ignore random packets
      await socket.send(packet.encode(query), remoteAddr);

    const databaseConnection = await r.connect(databaseOptions);

    const [queryResult] = await Promise.all(questions?.map(async(question) => {
      const { name: QuestionName, type: QuestionType } = question;

      if (QuestionType === "ANY") {
        const records = await r.table("record")
          .filter({ name: QuestionName })
          .run(databaseConnection);

        databaseConnection.close();

        if (records.length) {
          records.map(record => {
            const { class: class_, data, name, ttl, type } = record;
            query.answers?.push({ class: class_, data, name, ttl, type });
          });
        }

        return query;
      }

      let response = await r.table("record")
        .filter({ name: QuestionName, type: QuestionType })
        .limit(1)
        .run(databaseConnection);

      databaseConnection.close();

      if (response && response[0])
        response = response[0];

      if (Object.keys(response).length) {
        const { class: class_, data, name, ttl, type } = response;
        query.answers?.push({ class: class_, data, name, ttl, type });
      }

      return query;
    }));

    const encodedQuery = packet.encode(queryResult);
    await socket.send(encodedQuery, remoteAddr);
  }
```

**Comment by NetOpWibby** [comment]
<img width="843" alt="SS 2022-07-01 at 10 23 29 AM" src="https://user-images.githubusercontent.com/1288356/176941693-d0ac3e15-099c-4717-b23b-7b193a71ee70.png">

The way you handle deps in Deno is to list them in a single file and then just import the modules you need from there.
