### ISSUE TITLE
request .group() return never type

### ISSUE THREAD

**Issue by Upd4ting** [rethinkdb/rethinkdb-ts#105]
**Describe the bug**
When I do a request like that
```
 r.table('test').group('app_room_country') .count().run()
```

.group returns a never type so it does not compile

**To Reproduce**
Do the simple request above

**Expected behavior**
It should return a correct type as this request is totally valid in reql.

**System info**
 - OS: Linux 5.10.16.3-microsoft-standard-WSL2 x86_64
 - RethinkDB Version: 2.4.2~0bullseye
 - (its the docker image of rethinkdb)

**Comment by atassis** [comment]
I have also tested this and it works as intented. Closing. If you have more proper details- add them, but the latest commit does the job without any issues
