### ISSUE TITLE
Not all objects emitted when using `pipe()`

### ISSUE THREAD

**Issue by dominykas** [rethinkdb/rethinkdb-ts#108]
**Describe the bug**

I'm still debugging this, so opening this up for awareness, just in case someone can guess what the issue is (I can see some changes on how `destroy` / `close` / `end` happen now).

Basically, if I do `cursor.on('data')`, I get all objects. If instead I `cursor.pipe(anotherStream)`, then `anotherStream` receives fewer objects. It seems this is because the last few `data` events arrive after the `end` is emitted.

**To Reproduce**

See test case added in https://github.com/rethinkdb/rethinkdb-ts/pull/111

**Expected behavior**

All objects get emitted.

**System info**
 - OS: macOS and Linux
 - RethinkDB Version: 2.4.2
 - Node.js versions: 16 and 18

**Comment by dominykas** [comment]
Yes, the test I have in #109 is also failing on node@14.

**Comment by atassis** [comment]
Thanks! I have a pretty rough December, but will try to fix it in spare time

**Comment by dominykas** [comment]
Just testing things out, I reverted the `cursor.ts` changes from https://github.com/rethinkdb/rethinkdb-ts/commit/5cb4f4cddf6d69f575b9ae6ceba3751071caa9ae and https://github.com/rethinkdb/rethinkdb-ts/commit/52416537557f4da04aad1e6790885c8a5064dcab and then simply renamed the `private closed` to `private _closed` so that it does not collide with the one inheritted from the `Stream` and all tests (incl. my repro test case) seem to pass on Node.js 14, 16 and 18.

I don't know if this is the right thing to do, though, but my hunch is that `Cursor.closed` might have never been intended to override the `Readable.closed`? Otherwise why declare it as a `private` at all?

**Comment by dominykas** [comment]
Ah, I didn't realize that `Readable.closed` was only introduced in Node.js 18 - so it seems that naming collision was definitely unintended and the `Cursor.closed` was not being used for `Stream` purposes in Node.js, so my guess is that it's safe to simply rename?

I'm happy to open a PR with the change to revert `cursor.ts` changes and rename the `closed` to `_closed` if that's acceptable?

**Comment by atassis** [comment]
You can try to make it if lib keeps working properly:)

**Comment by atassis** [comment]
And yes, you are right about accidental overlapping- I wanted to rewrite the logic of the cursor (I did some job earlier and wanted to stabilize it)
Though your approach is better in many ways (simple and fast)

**Comment by dominykas** [comment]
OK, updated #111 with the code. The tests do pass... https://github.com/dominykas/rethinkdb-ts/actions/runs/3900771040
