### ISSUE TITLE
rethinkdb-ts is working well with node 20

### ISSUE THREAD

**Issue by iambumblehead** [rethinkdb/rethinkdb-ts#119]
Hey there @atassis this message is to share with you that rethinkdb-ts has been working well with node 20 here. It is powering services with changefeeds and complex queries and no issues encountered so far.
```diff
  "engines": {
-    "node": ">=12.x <=18.x"
+    "node": ">=16.x <=20.x"
  },
```

**Comment by dannytech** [comment]
Hi,

Is there any possibility of revisiting this issue now that 20 is the LTS version? Thanks!

**Comment by atassis** [comment]
Thanks fo reminding, `2.6.0` is published 👍🏼
