### ISSUE TITLE
indexCreate(): Typing Disallows Buffer for indexFunction

### ISSUE THREAD

**Issue by ChrisTalman** [rethinkdb/rethinkdb-ts#12]
The [`indexCreate()`](https://rethinkdb.com/api/javascript/index_create/) command can accept its optional argument `indexFunction` as a `Buffer`. However, the module typing seems to disallow this at the moment. It seems that `Buffer` could be added to the available types for `indexFunction`. I can submit a PR, unless someone else wishes to handle this.

**Comment by ronzeidman** [comment]
try 2.4.0-rxc.12

**Comment by ChrisTalman** [comment]
Thanks, it seems to be fixed. 👍 @ronzeidman
