### ISSUE TITLE
Transactions implement

### ISSUE THREAD

**Issue by tommmn** [rethinkdb/rethinkdb-ts#18]
Hey, I would like to know what is the best practice to implement kind of transaction flow.
I know that in other DB's there are built-in methods to achieve that, but here I didn't find one solid answer.
Basic flow:
 1. Successful payment
 2. Update Transactions history table
 3. Update User privileges

The main problem is between the last steps, I could do it in one query with .do() , but if it will fail, both will be gone, although the payment already registered.
So, any suggestions specific to RethinkDB (Job queue is already a consideration)?
thanks!

**Comment by ronzeidman** [comment]
Transactions are not implemented in RethinkDB. there is a possibility to simulate transactions in the driver but it will work only for projects using only this driver (or probably a different library on top of this driver) and will require specific fields/tables in the database. Its currently not in the scope of this project

**Comment by ChrisTalman** [comment]
This isn't possible right now. However, there's some hope that the ReQL-on-FoundationDB project could allow for transactions in ReQL, given that FoundationDB has transactions. Unfortunately, through, I'm not aware of any movement on that project yet. Last I heard the challenge was to find people to fund the project. [There's some more detail here.](http://samuelhughes.com/blog/10.html)

**Comment by maeb** [comment]
It is possible to implement distributed locking using RethinkDB. See [_Atomically updating a document based on a condition_](https://www.rethinkdb.com/docs/cookbook/javascript/#manipulating-documents).

**Comment by ChrisTalman** [comment]
@maeb Unfortunately, atomicity is limited to a single document. Atomicity cannot be guaranteed across more than one document in a table, or across multiple tables.

Single-document atomicity is certainly powerful. I've used it to simulate rudimentary transactions in a single table to prevent 'duplicate' documents, based upon multiple document fields. However, this is still ultimately unsafe, as there are some edge cases where failure will occur. It's also inflexible; the functionality has to be built for a specific purpose, such as deduplication within a single table, and as such is difficult to extend to more varied and complex query use cases, such as the one @tommmn mentions, which involves multiple writes across multiple tables.

**Comment by atassis** [comment]
@tommmn Transactions should be implemented on database level. An issue should be opened on main rethinkdb repo, not in the js driver repo. And yes, there is still nothing done in ReDB for transactions. Closing an issue.
