### ISSUE TITLE
Module not found error while compiling 

### ISSUE THREAD

**Issue by basavantrayagouda** [rethinkdb/rethinkdb-ts#19]
ERROR in ./node_modules/rethinkdb-ts/lib/connection/handshake-utils.js
Module not found: Error: Can't resolve 'crypto' in '\node_modules\rethinkdb-ts\lib\connection'
ERROR in ./node_modules/rethinkdb-ts/lib/connection/master-pool.js
Module not found: Error: Can't resolve 'net' in '\rethinkdb-ts\lib\connection'
ERROR in ./node_modules/rethinkdb-ts/lib/connection/socket.js
Module not found: Error: Can't resolve 'net' in '\rethinkdb-ts\lib\connection'
ERROR in ./node_modules/rethinkdb-ts/lib/response/cursor.js
Module not found: Error: Can't resolve 'stream' in '\rethinkdb-ts\lib\response'
ERROR in ./node_modules/rethinkdb-ts/lib/connection/socket.js
Module not found: Error: Can't resolve 'tls' in '\node_modules\rethinkdb-ts\lib\connection'

typescript version 3.2.1

while compiling getting above mentioned error, any help could be greatly helpful.

**Comment by ronzeidman** [comment]
Seems like you are trying to compile this module in a non-node environment (probably browser). this drive supports only node environment... sorry
