### ISSUE TITLE
.hasFields() typings don't allow nested field syntax

### ISSUE THREAD

**Issue by lenovouser** [rethinkdb/rethinkdb-ts#23]
Using:

```ts
.filter(row => row.hasFields({ a: { b: true } }).not())
```

fails with

```
Argument of type '{ a: { b: boolean; }; }' is not assignable to parameter of type 'string'.
```

which should be possible according to [rethinkdb.com/api/javascript/has_fields](https://rethinkdb.com/api/javascript/has_fields):

![](https://i.lenovouser.me/lfZ2PtD3fqwDNLPP.jpg)

**Comment by ronzeidman** [comment]
Thanks, I'll look into it and approve your pull request soon

**Comment by lenovouser** [comment]
Alright, no worries.

The PR is for `.update()` and `.filter()` - not this issue. Even though they are similar.

`.hasFields()` doesn't allow objects in the first place right now so I didn't know how to add the `DeepPartial` to it.
