### ISSUE TITLE
do().concatMap() Lacks Call Signature

### ISSUE THREAD

**Issue by ChrisTalman** [rethinkdb/rethinkdb-ts#24]
I'm using `2.4.0-rc.13` with a query resembling the following.

```TypeScript
r
	.expr({userId: '123'})
	.do(variables => r.table('Users').getAll(variables('userId')))
	.concatMap(variables => r.expr([variables]));
```

Unfortunately, it causes the following type error.

> Cannot invoke an expression whose type lacks a call signature. Type '(<U = any>(...args: (RStream<any> | ((arg: RDatum<any>, ...args: RDatum<any>[]) => any))[]) => RStream<U>) | (<Res = any, U = {}>(...args: (RStream<any> | ((arg: RDatum<U>, ...args: RDatum<any>[]) => any))[]) => RDatum<Res[]>)' has no compatible call signatures.

I've looked into the types, but haven't found the issue. It seems as though `concatMap()` might not be willing to accept the selection returned by `do()`.

Any help would be much appreciated. 😃

**Comment by ronzeidman** [comment]
try to add after `getAll(variables('userId')).coerceTo('array')`
