### ISSUE TITLE
can not update using object notation

### ISSUE THREAD

**Issue by GaikwadPratik** [rethinkdb/rethinkdb-ts#29]
@ronzeidman 

After updating from `2.4.0-rc.13` to `2.4.0-rc.15`, following line:
```
r.table<IAlert>(Table.Alert).get(this.alert.id).update({ count: r.row('count').add(1) }).run()
```
fails compilation with error 
![image](https://user-images.githubusercontent.com/5595263/60047409-ab51be80-9697-11e9-8869-7571203fb796.png)

However switching to anonymous function compiles successfully
```
r.table<IAlert>(Table.Alert).get(this.alert.id).update((row: RDatum<IAlert>) => row('count').add(1)).run()
```

Also how do I update multiple values using anonymous/lamda function?

**Comment by GaikwadPratik** [comment]
@ronzeidman , @lenovouser,

Can you please assist here? Its show stopper for me right now...

**Comment by lenovouser** [comment]
@GaikwadPratik what TypeScript version are you using?

**Comment by lenovouser** [comment]
@GaikwadPratik for me it also fails with `2.4.0-rc.12` and `2.4.0-rc.13` so it's not a issue caused by the update of the library. Also I don't know how TypeScript should even infer the correct value of a row if you're not using a function

**Comment by GaikwadPratik** [comment]
@lenovouser , @ronzeidman 

[official update](https://www.rethinkdb.com/api/javascript/update/) page suggest that we can use object notiation. So how do you guys write the queries? without `T`? how would one get advantage of using compile time validation?
