### ISSUE TITLE
RTable#{indexStatus,indexWait} being unaccurate

### ISSUE THREAD

**Issue by kyranet** [rethinkdb/rethinkdb-ts#3]
According to the following lines, they do not return an array:

https://github.com/rethinkdb/rethinkdb-ts/blob/a8403fb4d0507f0e390061ec18b8df5d7215dcff/src/types.ts#L941-L942

However, according to the official API documentation [index_status](https://www.rethinkdb.com/api/javascript/index_status/) and [index_wait](https://www.rethinkdb.com/api/javascript/index_wait/) they effectively return arrays.

Example reproducible code:

```typescript
r.table(table).indexStatus(index).nth(0)('ready').run();
```

Currently, TypeScript will complain with:

```
[ts] Cannot invoke an expression whose type lacks a call signature. Type 'never' has no compatible call signatures.
```

From the `.nth` call:

https://github.com/rethinkdb/rethinkdb-ts/blob/a8403fb4d0507f0e390061ec18b8df5d7215dcff/src/types.ts#L422-L424

Since it's not creating the RDatum with `IndexStatus[]` thus not extending arrays, it'll always imply the type `never`.

**Comment by ronzeidman** [comment]
Good catch, fixed
