### ISSUE TITLE
support table & index schema?

### ISSUE THREAD

**Issue by mattkrick** [rethinkdb/rethinkdb-ts#39]
Love the driver! Thank you so much for the work you've put into it.

Are you opposed to a way to instantiate `r` so we could pass in a type schema? I'm looking for a way to get type information automatically without having to inject it into every query.

Rough idea:

```ts
// changes to driver types
table<T extends keyof Tables>(tableName: RValue<T>): RTable<Tables[T]>

// user code
interface IUser {
  name: string
}
interface Tables {
  User: IUser
}
const r = new R<Tables, Indexes>()
r.table('Foo') // error! Foo isn't a table
r.table('User').update({name: 1}) // error! name should be a string
await r.table('User').run() // returns IUser[] 
```

I'm sure there are some gotchas since the `tableName` could be a function, but I figure it'd be a nice little check that works for most use cases

**Comment by atassis** [comment]
Closing this issue due to https://github.com/rethinkdb/rethinkdb-ts/pull/46#issuecomment-633056640
