### ISSUE TITLE
Update for RethinkDB 2.4.0

### ISSUE THREAD

**Issue by McSneaky** [rethinkdb/rethinkdb-ts#43]
Since RethinkDB 2.4.0 was released it would be cool to get updates for TS driver to support its new features :slightly_smiling_face: 

https://github.com/rethinkdb/rethinkdb/releases/tag/v2.4.0

**Comment by ronzeidman** [comment]
But operations and write hooks are supported. Something else needs to be added?

**Comment by McSneaky** [comment]
:open_mouth: It is indeed, for some reason I didn't notice bitwise ops..

Thnx for great driver! :yum:
