### ISSUE TITLE
`connectPool` has wrong type definition

### ISSUE THREAD

**Issue by freewind** [rethinkdb/rethinkdb-ts#6]
In definition, it has a return type of `Promise<MasterPool>`:

https://github.com/rethinkdb/rethinkdb-ts/blob/b0d0dbbe6c5a00611788e8ac6695b17421aa3636/src/types.ts#L1067

But in the code, it doesn't return anything:

https://github.com/rethinkdb/rethinkdb-ts/blob/e030e4712be7515046c5f48612d84831afbc67a3/src/query-builder/r.ts#L19-L56

**Comment by ronzeidman** [comment]
thanks, fixed
