### ISSUE TITLE
hasFields(): RDatum <string> Not Allowed

### ISSUE THREAD

**Issue by ChrisTalman** [rethinkdb/rethinkdb-ts#61]
In some situations, `hasFields()` does not seem to allow `RDatum <string>`.

I'm not sure what the precise conditions are in which this happens. Typically, I'm checking for a field on a document.

I'm using `rethinkdb-ts@2.4.2`.

**Comment by atassis** [comment]
I know this bug. Typing is wrong. Will try to fix this as soon as I can. But still it is better if you provide the code=)

**Comment by atassis** [comment]
@ChrisTalman can you provide a working example of query, which works in admin panel, but throws in code?

**Comment by ChrisTalman** [comment]
```TypeScript
r
	.table<Fruit>('Fruits')
	.filter
	(
		fruit => fruit
			.keys()
			.filter
			(
				key => fruit
					.hasFields(key)
			)
			.count()
			.gt(0)
	);
```

**Comment by atassis** [comment]
I think i have fixed that right now in the https://github.com/rethinkdb/rethinkdb-ts/pull/66. I'll wait for tomorrow if all my PRs can be reviewed by teammates and then will merge them all and deploy a new version. It will be appreciated if you can review all versions from 2.4.3 and above and create issues if something happens. I am going to help rethinkdb team with JS stuff for a while
