### ISSUE TITLE
TypeScript type definition does not allow match commands in filter

### ISSUE THREAD

**Issue by syy1125** [rethinkdb/rethinkdb-ts#68]
**Describe the bug**
Filtering using `match`, although valid in reql, shows up as an error for TypeScript.

**To Reproduce**
```
r.expr(['foo', 'bar']).filter(word => word.match('^f'))
```
The expression above works as expected and returns `['foo']` (tested using data explorer in admin website).
However, TypeScript disallows this, with error message
```
Argument of type '(word: RDatum<string>) => RDatum<MatchResults>' is not assignable to parameter of type 'string | ((doc: RDatum<string>) => RValue<boolean>)'.
  Type '(word: RDatum<string>) => RDatum<MatchResults>' is not assignable to type '(doc: RDatum<string>) => RValue<boolean>'.
    Type 'RDatum<MatchResults>' is not assignable to type 'RValue<boolean>'.
      Type 'RDatum<MatchResults>' is not assignable to type 'RDatum<boolean>'.
        Types of property 'do' are incompatible.
          Type '<U>(...args: (RDatum<any> | ((arg: RDatum<MatchResults>, ...args: RDatum<any>[]) => U))[]) => U extends RStream<any> ? RStream<any> : RDatum<any>' is not assignable to type '<U>(...args: (RDatum<any> | ((arg: RDatum<boolean>, ...args: RDatum<any>[]) => U))[]) => U extends RStream<any> ? RStream<any> : RDatum<any>'.
            Types of parameters 'args' and 'args' are incompatible.
              Type 'RDatum<any> | ((arg: RDatum<boolean>, ...args: RDatum<any>[]) => any)' is not assignable to type 'RDatum<any> | ((arg: RDatum<MatchResults>, ...args: RDatum<any>[]) => any)'.
                Type '(arg: RDatum<boolean>, ...args: RDatum<any>[]) => any' is not assignable to type 'RDatum<any> | ((arg: RDatum<MatchResults>, ...args: RDatum<any>[]) => any)'.
                  Type '(arg: RDatum<boolean>, ...args: RDatum<any>[]) => any' is missing the following properties from type 'RDatum<any>': do, getField, nth, default, and 102 more.ts(2345)
```

**Expected behavior**
Type definition should be able to express that `RDatum<MatchResult>` can be converted into a boolean expression.

**System info**
 - OS: Ubuntu 18.04.4 bionic LTS
 - RethinkDB Version: rethinkdb 2.4.0~0bionic (CLANG 6.0.0 (tags/RELEASE_600/final))
 - `typescript` Version: v3.9.6
 - `rethinkdb-ts` Version: v2.4.4

**Additional context**
When trying to find a workaround for this, I also found that `coerceTo('bool')` is invalid, even though it's valid reql.

**Comment by atassis** [comment]
@syy1125 I'll try to fix in next several days, but it would be nice if you test the 2.4.5 version of package

**Comment by syy1125** [comment]
Still an issue on 2.4.5

**Comment by syy1125** [comment]
Also, `coerceTo('bool')` is valid reql, but for some reason it not documented at https://rethinkdb.com/api/javascript/coerce_to?
I'm bringing this up because I'm playing with the idea that, instead of changing the callback return type to `RDatum<any>` (which seems to be the obvious solution), perhaps users should be required to do `coerceTo('bool')`.

I'm assuming this is what rethinkdb does under the hood anyway. The advantage is that it keeps typescript maximally useful. But of course the issue of "valid reql is not valid in typescript" still exists.
... or it could just be `@typescript-eslint/no-explict-any` is rubbing off on me.

**Comment by atassis** [comment]
About `coerceTo('bool')`- it is documentation's error, will report this.
About making coerceTo thing required in type- definitely not.
About the bug: next thing works fine
```typescript
  const query = r.expr(['foo', 'bar']).filter((word) => word.match('^f'));
  const result = await pool.run(query);
```
Closing an issue, might work long time ago
