### ISSUE TITLE
merge(): Object from Callback Disallowed

### ISSUE THREAD

**Issue by ChrisTalman** [rethinkdb/rethinkdb-ts#69]
The following kind of query yields a type error:

```JavaScript
r
	.table('Fruits')
	.merge
	(
		fruit =>
		(
			{
				merged: 1
			}
		)
	)
```

The type definitions seem to expect that the callback will return an `RDatum`, and so do not accept a raw JavaScript object.

It's valid ReQL for the callback to simply return a raw JavaScript object.

**Comment by atassis** [comment]
I'll fix that in next several days.

**Comment by atassis** [comment]
@ChrisTalman What is the version of the package you use? Checked right now on latest- cant reproduce

**Comment by ChrisTalman** [comment]
`2.4.2`.

If you can't reproduce it, then it's probably fixed.

I'll reopen this if I encounter it in `2.4.5` or later.
