### ISSUE TITLE
wanted to say thank you

### ISSUE THREAD

**Issue by iambumblehead** [rethinkdb/rethinkdb-ts#74]
I've been using this package and other rethink-related packages such as thinky and rethinkdbdash in various projects. rethinkdb-ts is my favorite and rethinkdb-ts is the main thing that keeps rethinkdb usable for me.

Thank you for what you do :)

**Comment by atassis** [comment]
Hello, @iambumblehead. This library is most updated one compared to all others. Worth noting, we have longterm plans to update current repo heavily and move it `rethinkdb` npm package (as well as deprecating all other repos and setting current as single official one).

**Comment by iambumblehead** [comment]
thank you @atassis I will look forward that
