### ISSUE TITLE
Node multipleResolves warning is firing on connect

### ISSUE THREAD

**Issue by murrayju** [rethinkdb/rethinkdb-ts#76]
**Describe the bug**
The node warning event `multipleResolves` is being triggered shortly after connecting via `r.connectPool()`.

**To Reproduce**
1. Register the multipleResolves handler
```
  process.on('multipleResolves', (type, promise, reason) => {
    console.error('Node<multipleResolves>', { type, reason });
  });
```
2. Connect to a db
3. Wait about 20 seconds

**Expected behavior**
The multipleResolves handler should not be triggered.

**System info**
 - OS: macOS, docker (`node:14` base)... likekly not os specific
 - RethinkDB Version: 2.4.1

**Additional context**
This was introduced in 2.4.6 (did not happen in 2.4.5) and is still present in 2.4.8.

**Comment by atassis** [comment]
I'll test and fix this in several days

**Comment by atassis** [comment]
@murrayju this happens due to the opened issue in [node](https://github.com/nodejs/node/issues/24321). Can you describe the case where it disturbs you? Can't call [this ](https://github.com/rethinkdb/rethinkdb-ts/blob/main/src/connection/connection.ts#L120) a bug

**Comment by murrayju** [comment]
Thanks for the quick response. I'm aware of the node issue, I was only concerned because this was a change in behavior that I didn't expect from a patch release, and _might_ have been sign of a problem. The implementation using `Promise.race` totally explains it, so I'm satisfied.
