### ISSUE TITLE
Docs outdated from current default Node Package

### ISSUE THREAD

**Issue by Taha-Firoz** [rethinkdb/rethinkdb-ts#78]
When installing this package via NPM we get a default version of "3.0.0-alpha.0" however there have been some substantial API changes in that version that makes a majority of the current documentation inapplicable. It's either that or modules were broken down differently because downgrading to  "2.4.8"  get's everything working like the docs again.

**Comment by atassis** [comment]
Crap. I have asked to unpublish this version, but it wasn't. Thanks for the notice. I am preparing a new version of rethinkdb-ts with separated logic to make it more maintainable (with some major fixes with pooling)

**Comment by atassis** [comment]
I'll close this when unpublishing ld be done

**Comment by atassis** [comment]
I have pushed 2.4.9, which is the same as 2.4.8, so it might work the same
