### ISSUE TITLE
what is the recommended way to perform a health check?

### ISSUE THREAD

**Issue by iambumblehead** [rethinkdb/rethinkdb-ts#79]
would you recommend either of these calls for usage with a health check function?
```javascript
r.getPoolMaster().isHealthy
```

```javascript
await r.table( 'tableInTheDb' ).limit( 1 ).pluck( 'id' ).run();
```

**Comment by atassis** [comment]
Well, I can't get a proper answer, but `isHealthy` is not enough, as I think. The better is to run `r.expr(1).add(1)`, for example. Not calling any table, just asking for result the db.

**Comment by iambumblehead** [comment]
thanks for the response
