### ISSUE TITLE
RethinkDB question, better to use one big table or two separate tables?

### ISSUE THREAD

**Issue by iambumblehead** [rethinkdb/rethinkdb-ts#80]
@atassis I hope it is OK to ask your opinion here regarding RethinkDB data: given a large set of data, is it better to use one big table or two separate tables?

I searched for answers but mostly found advice for DynamoDB users recommending one giant table for everything.

For example, "TablePets"
Or "TableCatPets" and "TableDogPets"

For a large set of "dog" and "cat" type documents, otherwise the same, is there any performance benefit to using two tables rather than one? Would inserts or joins to other table be faster or slower for either case?

**Comment by atassis** [comment]
Btw, you don't have to ping me directly, as I am watching all the issues in Github on spare time=)

**Comment by iambumblehead** [comment]
@thelinuxlich recommended one table and that's what I'm going with here, closing this ticket
