### ISSUE TITLE
Type 'string[]' is not assignable to type 'MultiFieldSelector'.

### ISSUE THREAD

**Issue by BannerBomb** [rethinkdb/rethinkdb-ts#81]
**Describe the bug**
When using TypeScript the "pluck" should be able to accept an object with keys that have an array of strings according to the ReQL documentations [here](https://rethinkdb.com/docs/nested-fields/javascript/). Such as
```ts
.pluck({ key: ['nested_key', 'second_nested_key', ...] })
```

but instead, it errors with the following
```ts
Type 'string[]' is not assignable to type 'MultiFieldSelector'.
  Type 'string[]' is not assignable to type '{ [property: string]: MultiFieldSelector; }'.
    Index signature is missing in type 'string[]'.ts(2322)
```

**To Reproduce**
 - See the **Describe the bug** section above.

**Expected behavior**
Any method that allows providing nested object values, should also be allowed to accept the shorthand form.

**Screenshots**
![image](https://user-images.githubusercontent.com/11788894/116006778-bd298300-a5da-11eb-84b2-11163d5ebf69.png)
![image](https://user-images.githubusercontent.com/11788894/116006821-e77b4080-a5da-11eb-97e6-aa60c466918b.png)

**System info**
 - OS: Ubuntu 18.04.2 LTS
 - RethinkDB Version: 2.4.0

**Additional context**

**Comment by atassis** [comment]
Fixed in v2.4.10, try it
