### ISSUE TITLE
Using cursor as an async iterator throws when it reaches the end

### ISSUE THREAD

**Issue by lerouxb** [rethinkdb/rethinkdb-ts#86]
According to the readme:

> A cursor is already a readable stream, no need for toStream()
> A readable stream is already an async iterator in node 10 no need for .asyncIterator()

So according to my limited understanding of async iterators this should work:

```javascript
const connection = await R.connect(options);
const query = R.db(dbName).table(tableName);
const cursor = await query.getCursor(connection);

for await (const row of cursor) {
    console.log(JSON.stringify(row));
}
```

But this prints every row and then throws `RethinkDBError [ReqlDriverError]: No more rows in the cursor.` Shouldn't it just exit the loop when it reaches the end? I'm using node 14.

**Comment by atassis** [comment]
Have tested now, it breaks on small amount of data, it seems, will try to fix later

**Comment by atassis** [comment]
You can test it in `2.4.11`, might be fixed

**Comment by lerouxb** [comment]
Thanks! I tested this and it works for me now.
