### ISSUE TITLE
Does not work with Deno

### ISSUE THREAD

**Issue by pavel-kolesnikov** [rethinkdb/rethinkdb-ts#89]
**Is your feature request related to a problem? Please describe.**
Deno can't use this overall great library because it requires at least `net` and `tls` built-ins Node.js which are not covered by shims on the Deno side.

**Describe the solution you'd like**
It would be tremendously great if the library drops  Node.js buildin dependencies to support Deno and browser scenarios.

**Describe alternatives you've considered**
I've tried a whole bunch of different solutions that converts `npm` modules to ESM.

For example with `esm.sh`:
```
PS deno-app> deno cache https://esm.sh/rethinkdb-ts
Download https://esm.sh/rethinkdb-ts
Download https://cdn.esm.sh/v43/rethinkdb-ts@2.4.14/deno/rethinkdb-ts.js
Download https://cdn.esm.sh/v43/rethinkdb-ts@2.4.14/lib/index.d.ts
Download https://cdn.esm.sh/v43/rethinkdb-ts@2.4.14/lib/types.d.ts
Download https://cdn.esm.sh/v43/rethinkdb-ts@2.4.14/lib/error/error.d.ts
Download https://cdn.esm.sh/v43/rethinkdb-ts@2.4.14/lib/query-builder/r.d.ts
Download https://cdn.esm.sh/v43/rethinkdb-ts@2.4.14/lib/response/cursor.d.ts
Download https://cdn.esm.sh/error.js?type=unsupported-nodejs-builtin-module&name=tls&importer=rethinkdb-ts
Download https://cdn.esm.sh/error.js?type=unsupported-nodejs-builtin-module&name=net&importer=rethinkdb-ts
Download https://cdn.esm.sh/v43/@types/node/tls
Download https://cdn.esm.sh/v43/@types/node/stream
Download https://cdn.esm.sh/v43/@types/node/net
Download https://cdn.esm.sh/v43/@types/node/events
Download https://cdn.esm.sh/v43/rethinkdb-ts@2.4.14/lib/internal-types.d.ts
Download https://cdn.esm.sh/v43/rethinkdb-ts@2.4.14/lib/proto/enums.d.ts
Download https://cdn.esm.sh/v43/rethinkdb-ts@2.4.14/lib/connection/socket.d.ts
Download https://cdn.esm.sh/v43/rethinkdb-ts@2.4.14/lib/connection/data-queue.d.ts
```
Here we see that at least `tls` and `net` are not supported.

With `jspm.dev`:
```TypeScript
import { r } from "https://esm.sh/rethinkdb-ts";
const conn = await r.connectPool({ host: 'localhost', port: 28015 })
await r.db('test').tableCreate('tv_shows').run(conn)

const res = await r.db('test').table('tv_shows').insert({ name: 'Star Trek TNG' }).run(conn)
console.log(res)
```
Launch:
```
PS deno-app> deno.exe run -A --unstable .\rethinkdb.ts
Check file:///C:/Users/user/Documents/works/deno/tms/deno-app/rethinkdb.ts
Error: Node.js net module is not supported by jspm core. Deno support here is tracking in https://github.com/jspm/jspm-core/issues/4, +1's are appreciated!
ReqlDriverError: Unable to establish connection, see cause for more info.
error: Uncaught ReqlDriverError: Error initializing master pool
              reject(new error_1.RethinkDBError("Error initializing master pool", {
                     ^
    at MasterConnectionPool.<anonymous> (http://jspm.dev/npm:rethinkdb-ts@2.4.14!cjs:3381:22)
    at Object.a (http://jspm.dev/npm:@jspm/core@2.0.0-beta.7/nodelibs/events:1:1593)
    at MasterConnectionPool.o.emit (http://jspm.dev/npm:@jspm/core@2.0.0-beta.7/nodelibs/events:1:3311)
    at MasterConnectionPool.setHealthy (http://jspm.dev/npm:rethinkdb-ts@2.4.14!cjs:3564:14)
    at ServerConnectionPool.<anonymous> (http://jspm.dev/npm:rethinkdb-ts@2.4.14!cjs:3555:14)
    at ServerConnectionPool.o.emit (http://jspm.dev/npm:@jspm/core@2.0.0-beta.7/nodelibs/events:1:3369)
    at ServerConnectionPool.setHealthy (http://jspm.dev/npm:rethinkdb-ts@2.4.14!cjs:3040:14)
    at ServerConnectionPool.persistConnection (http://jspm.dev/npm:rethinkdb-ts@2.4.14!cjs:3121:18)
```

**Comment by atassis** [comment]
This package is written for node js first, so using this in Deno is not any kind of required feature. Still, I have researched a little, what's happening around the Deno-Node.js compatibility- `net` and `tls` are not yet there. If there are any instruments for keeping both node and Deno in a single codespace- I can do this. But I need help from someone with this issue since I see no big effort from spending my time on it right now.

**Comment by atassis** [comment]
Если вкратце- могу запилить форк, если подскажешь, чем заменить net и tls в дено. Но, скорее всего, в модуль оно не попадет, так как дено работает с пакетами иначе и с нодой оно не заработает

**Comment by pavel-kolesnikov** [comment]
> This package is written for node js first, so using this in Deno is not any kind of required feature. Still, I have researched a little, what's happening around the Deno-Node.js compatibility- `net` and `tls` are not yet there. If there are any instruments for keeping both node and Deno in a single codespace- I can do this. But I need help from someone with this issue since I see no big effort from spending my time on it right now.

Understood. In the README it says the old `rethinkdbdash` module supported browser and browser support is considered to be a thing if there's a demand. I assume browsers has limited support for built-in Node.js modules like `net` or `tls`...

> Если вкратце- могу запилить форк, если подскажешь, чем заменить net и tls в дено. Но, скорее всего, в модуль оно не попадет, так как дено работает с пакетами иначе и с нодой оно не заработает

There is a [port](https://github.com/lucacasonato/rethinkdb-deno) that does not work for me either... 
Так что если сможешь взглянуть, чем они заменили `net` и `tls` --- будет круто. Я только второй день вожусь с deno и rethinkdb, поэтому довольно бесполезен в практическом плане...

**Comment by atassis** [comment]
Так зачем тебе сразу две херово работающие технологии, тебе ресинка не хватает?)
А так я не знаю, как работал rethinkdbdash, но тут сокетное соединение. Если в старом модуле использовался http- понятно, почему дэш работал, но это хреновая затея для бд либы.
В общем, я сам даже не трогаю дено, пока он сколь-нибудь prod реди не станет, но не вижу смысла сколь-нибудь сильно париться. Пока что я не вижу нормальных способов переехать кроме как самим форкнуть и переписать использование сокетов. Могу так сделать, но текущий репозиторий сильно не об этом, так что закрываю ишью

**Comment by atassis** [comment]
Long story short- closed an issue due to unreadiness of Deno for simple migration the current codebase and lack of any necessity since Deno is still not that production-ready technology. Later the question can be discussed again, but not now.
