### ISSUE TITLE
TLS

### ISSUE THREAD

**Issue by ChrisTalman** [rethinkdb/rethinkdb-ts#9]
Does `rethinkdb-ts` support TLS connections?

I can't find any documentation on its usage.

**Comment by ChrisTalman** [comment]
Having looked into the code, it seems that TLS connections are supported. The subtle difference from the old official driver is that the property in the options object is `tls`, [rather than `ssl`](https://rethinkdb.com/api/javascript/connect/). The full set of options can be [viewed in the Node documentation](https://nodejs.org/api/tls.html#tls_tls_connect_options_callback), although likely only the `ca` property is relevant. Perhaps it could be helpful to note this somewhere in the `README.md`?

**Comment by ChrisTalman** [comment]
I should note, though, that I'm having trouble getting TLS to work.

I attempt to create a pool:

```TypeScript
RethhinkDB.connectPool({host: 'rethink', tls: {ca: certificate}});
```
However, the promise is rejected, and the Rethink server reports that the handshake failed:
```
Driver connection TLS handshake failed: Unknown protocol. By default, RethinkDB requires at least TLSv1.2. You can enable older TLS versions on the server through the `--tls-min-protocol TLSv1` option. If your client uses an older version of the OpenSSL library, you might also have to specify the option `--tls-ciphers EECDH+AESGCM:EDH+AESGCM:AES256+EECDH:AES256+EDH:AES256-SHA`. (OpenSSL error 336027900)
```
I've attempted to tweak the server options as it suggests, to no avail. In any case, so far as I'm aware, my Node version should use `TLSv1.2`. So, this error seems quite odd. The client and server are being run in Docker containers, although I'm not aware of any reason why this should be relevant to this error.

Perhaps there's some aspect of configuration that I'm overlooking?

**Comment by ronzeidman** [comment]
I see you saw my added support for tls, try connecting like this
```ts
RethhinkDB.connectPool({host: 'rethink', tls: true, ca: certificate});
```

**Comment by gustavopch** [comment]
That doesn't work here. I'm digging through the code in my node_modules and trying to understand what's happening.

Here's the connect snippet in my code:
```ts
r.connectPool({
  host: 'portal395-5.keffs.2947029280.composedb.com',
  port: 19194,
  user: ...,
  password: ...,
  tls: true,
  ca: caCert,
  rejectUnauthorized: false
})
```
But look at the content of `options` at the image below (which shows the code of the method `connect` at `connection/socket.js`). For some reason it ignores all the props apart from host and port.
![image](https://user-images.githubusercontent.com/10941958/49831379-e7b47180-fd7a-11e8-8c15-287cc110ccfc.png)

**Comment by ronzeidman** [comment]
sorry, try
```ts
r.connectPool({
  user: ...,
  password: ...,
  servers: [{
      host: 'portal395-5.keffs.2947029280.composedb.com',
      port: 19194,
      tls: true,
      ca: caCert,
      rejectUnauthorized: false
  }]
})
```

**Comment by gustavopch** [comment]
Perfect! That works. Thanks.

**Comment by ronzeidman** [comment]
Great, can I close the issue?

**Comment by ChrisTalman** [comment]
It seems that the `tls` property is not being passed along the chain of operations to `connect()` in `class RethinkDBSocket`. Unless there's a good reason for the current situation, it seems like it would be useful to change this behaviour, so that it is passed along. I could submit a PR, or someone else - I don't mind either way.

Also, it'd probably still be helpful for future troubleshooting for the `tls` property to be mentioned in the `README.md`.

**Comment by ronzeidman** [comment]
Added it to the readme, if something is unclear, suggest an edit.
The connection settings by design are encapsulated under server/servers property, I've added support for direct simple "host/port" settings for "backwards" (other driver's) compatibility.

**Comment by ronzeidman** [comment]
done

**Comment by ChrisTalman** [comment]
Oh, I see, I was not aware of that. This issue should be resolved, then. Thanks for the help!

As an aside, concerning the documentation, perhaps it might be helpful for newcomers if the `server` design is made clear at the start of the `README.md`, such as under the 'Initialize' section. In other words, it could be presented as the default way of going about things. In the current form of the documentation, it might be overlooked as being a sort of advanced feature, rather than the standard, and so people might be more likely to trip up before they dig deeper and realise what's up, as in my case.

**Comment by ronzeidman** [comment]
You're right, the documentation is really lacking, now you have to relying on rethinkdbdash, rethinkdb, the readme and the typings to provide sufficient documentation. I wanted to write the full documentation in the new open-rethink site which is supposed to declare this driver as the new official driver but it's delayed...
